// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgID.proto

#ifndef PROTOBUF_INCLUDED_MsgID_2eproto
#define PROTOBUF_INCLUDED_MsgID_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_MsgID_2eproto 

namespace protobuf_MsgID_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_MsgID_2eproto
namespace Vera {
}  // namespace Vera
namespace Vera {

enum MsgID {
  MsgNone_ID = 0,
  LoginReq_ID = 1,
  LoginAck_ID = 2,
  MsgID_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  MsgID_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool MsgID_IsValid(int value);
const MsgID MsgID_MIN = MsgNone_ID;
const MsgID MsgID_MAX = LoginAck_ID;
const int MsgID_ARRAYSIZE = MsgID_MAX + 1;

const ::google::protobuf::EnumDescriptor* MsgID_descriptor();
inline const ::std::string& MsgID_Name(MsgID value) {
  return ::google::protobuf::internal::NameOfEnum(
    MsgID_descriptor(), value);
}
inline bool MsgID_Parse(
    const ::std::string& name, MsgID* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MsgID>(
    MsgID_descriptor(), name, value);
}
enum ErrorCodeID {
  AckSuccess_0 = 0,
  ErrorCodeID_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ErrorCodeID_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ErrorCodeID_IsValid(int value);
const ErrorCodeID ErrorCodeID_MIN = AckSuccess_0;
const ErrorCodeID ErrorCodeID_MAX = AckSuccess_0;
const int ErrorCodeID_ARRAYSIZE = ErrorCodeID_MAX + 1;

const ::google::protobuf::EnumDescriptor* ErrorCodeID_descriptor();
inline const ::std::string& ErrorCodeID_Name(ErrorCodeID value) {
  return ::google::protobuf::internal::NameOfEnum(
    ErrorCodeID_descriptor(), value);
}
inline bool ErrorCodeID_Parse(
    const ::std::string& name, ErrorCodeID* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ErrorCodeID>(
    ErrorCodeID_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Vera

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::Vera::MsgID> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Vera::MsgID>() {
  return ::Vera::MsgID_descriptor();
}
template <> struct is_proto_enum< ::Vera::ErrorCodeID> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Vera::ErrorCodeID>() {
  return ::Vera::ErrorCodeID_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_MsgID_2eproto
